env: "local" # local, dev, prod

storage:
  host: "localhost"
  port: 5432
  user: "Elias"
  db_name: "journal"
  sslmode: "disable"
  max_open_conns: 10
 
grpc:
  host: "localhost"
  port: 4043
  timeout: 2m
