services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: Elias
      POSTGRES_PASSWORD: 2795749b040201cde46538c3b74b4d97
      POSTGRES_DB: sso_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
