env: "local" # local, dev, prod

postgres:
  host: "localhost"
  port: 5432
  user: "Elias"
  db_name: "sso_db"
  sslmode: "disable"
  max_open_conns: 10

grpc:
  host: "localhost"
  port: 4042
  timeout: 2m

redis:
  host: "localhost"
  port: 6379
  db: 0

mailtrap:
  host: "localhost"
  port: 1025
  username: ""
  sender_email: "eliaseromanov@gmail.com"
  use_tls: false

token:
  access_ttl: 90m
  refresh_ttl: 720h
  verification_ttl: 3m
