// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Person struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	PasswordHash []byte      `json:"password_hash"`
	UserRole     string      `json:"user_role"`
}

type RefreshSession struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	AppID     int32            `json:"app_id"`
	TokenID   []byte           `json:"token_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
