// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: person.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO person (
    email,
    username,
    password_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, email, username, password_hash, user_role
`

type CreatePersonParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash []byte `json:"password_hash"`
}

// Создает нового пользователя и возвращает всю строку
func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson, arg.Email, arg.Username, arg.PasswordHash)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.UserRole,
	)
	return i, err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM refresh_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserSessions, userID)
	return err
}

const deleteSessionByTokenID = `-- name: DeleteSessionByTokenID :exec
DELETE FROM refresh_sessions
WHERE token_id = $1
`

// Удаление токена (Logout или Refresh Token Rotation)
func (q *Queries) DeleteSessionByTokenID(ctx context.Context, tokenID []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenID, tokenID)
	return err
}

const getPersonById = `-- name: GetPersonById :one
SELECT
    id,
    email,
    username,
    password_hash,
    user_role
FROM person
WHERE id = $1
ORDER BY id
LIMIT 1
`

// Поиск профиля
func (q *Queries) GetPersonById(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonById, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.UserRole,
	)
	return i, err
}

const getPersonByLogin = `-- name: GetPersonByLogin :one
SELECT
    id,
    email,
    username,
    password_hash,
    user_role
FROM person
WHERE username = $1
ORDER BY id
LIMIT 1
`

// Поиск для авторизации
func (q *Queries) GetPersonByLogin(ctx context.Context, username string) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByLogin, username)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.UserRole,
	)
	return i, err
}

const getSessionByTokenID = `-- name: GetSessionByTokenID :one
SELECT
    id,
    user_id,
    app_id,
    token_id,
    expires_at
FROM refresh_sessions
WHERE
    token_id = $1
    AND expires_at > NOW()
ORDER BY expires_at
LIMIT 1
`

type GetSessionByTokenIDRow struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	AppID     int32            `json:"app_id"`
	TokenID   []byte           `json:"token_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

// Проверка токена при обновлении
func (q *Queries) GetSessionByTokenID(ctx context.Context, tokenID []byte) (GetSessionByTokenIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenID, tokenID)
	var i GetSessionByTokenIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.TokenID,
		&i.ExpiresAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    email,
    username,
    user_role
FROM person
ORDER BY username
`

type ListUsersRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Username string      `json:"username"`
	UserRole string      `json:"user_role"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRefreshToken = `-- name: SaveRefreshToken :one
INSERT INTO refresh_sessions (
    user_id,
    app_id,
    token_id,
    expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id
`

type SaveRefreshTokenParams struct {
	UserID    pgtype.UUID      `json:"user_id"`
	AppID     int32            `json:"app_id"`
	TokenID   []byte           `json:"token_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

// Сохраняет новую сессию рефреш-токена
func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveRefreshToken,
		arg.UserID,
		arg.AppID,
		arg.TokenID,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE person
SET password_hash = $2
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash []byte      `json:"password_hash"`
}

// Смена пароля
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE person
SET user_role = $2
WHERE id = $1
RETURNING id, email, username, password_hash, user_role
`

type UpdateRoleParams struct {
	ID       pgtype.UUID `json:"id"`
	UserRole string      `json:"user_role"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Person, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.UserRole)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.UserRole,
	)
	return i, err
}

const userExist = `-- name: UserExist :one
SELECT
    EXISTS(
        SELECT 1
        FROM person
        WHERE username = $1
    )
`

func (q *Queries) UserExist(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, userExist, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
