// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Создает нового пользователя и возвращает всю строку
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	DeleteAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	// Удаление токена (Logout или Refresh Token Rotation)
	DeleteSessionByTokenID(ctx context.Context, tokenID []byte) error
	// Поиск профиля
	GetPersonById(ctx context.Context, id pgtype.UUID) (Person, error)
	// Поиск для авторизации
	GetPersonByLogin(ctx context.Context, username string) (Person, error)
	// Проверка токена при обновлении
	GetSessionByTokenID(ctx context.Context, tokenID []byte) (GetSessionByTokenIDRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	// Сохраняет новую сессию рефреш-токена
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (pgtype.UUID, error)
	// Смена пароля
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Person, error)
	UserExist(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
